### ISSUE TITLE
Warning on overwriting remote file

### ISSUE THREAD

**Issue by norling** [NBISweden/sda-cli#200]
There is currently no feedback from the system whether a file exists in the remote when attempting to upload. This should be added, optionally with a `-f/--force` flag to automatically overwrite remote files.

The required refactoring to resolve the circular dependencies will also be part of the scope on this.
config should be move out of upload and into a new package.

**Comment by jbygdell** [comment]
This will be complicated to implement.
Mainly because the S3 backend doesn't care if you overwrite an existing file or not.
