### ISSUE TITLE
Warning on uploading unencrypted file

### ISSUE THREAD

**Issue by norling** [NBISweden/sda-cli#201]
To prevent wasting user time and inbox space, there should be a warning when attempting to upload an unencrypted file to the inbox. This can be checked either by the file ending or more reliably using the magic number in the first bytes of the file header.

The crypt4gh specification is available [here](https://samtools.github.io/hts-specs/crypt4gh.pdf).:

From the documentation:
> The current byte representation of the magic number and version is:
```
0x63 0x72 0x79 0x70 0x74 0x34 0x67 0x68 0x01 0x00 0x00 0x00
============= magic_number============= ===== version =====
```
(`crypt4gh` followed by `1`)

**Comment by pahatz** [comment]
Similar check implemented: https://github.com/NBISweden/sda-cli/pull/38/files
