### ISSUE TITLE
Clarify wildcard use for recursive uploads

### ISSUE THREAD

**Issue by norling** [NBISweden/sda-cli#204]
A comment from the external user testing was:
> For recursive uploading, it is unclear which wildcards should be used, . or *.

It should be clarified in text and examples how wildcards can be used.

**Comment by pahatz** [comment]
Minor documentation change: https://github.com/NBISweden/sda-cli/pull/207

**Comment by pahatz** [comment]
Thanks, I wasn't aware of the hidden files difference.
Is it common to have a directory of thousands of files? Then we could skip mentioning the `*` example since it will most probably won't work and just mention what `/.` does.

**Comment by kusalananda** [comment]
I'm sorry for the delay in responding. I'm not very good at spotting relevant things in the constant stream of Github notification emails that I get.

I think the current text should rather remove the use of the word "wildcard", and instead describe what adding a dot at the end of a directory path does.  

Using the star is not really a special case, it's just a way of listing multiple pathnames in a compact way, whereas using the dot is somewhat special.

I think we must assume that there may be users who have directories with several thousands of files that they want to work with. In those cases, using `*` will simply not work with _any_ command line tool.
