### ISSUE TITLE
sda-cli exits with zero status when it should not

### ISSUE THREAD

**Issue by aaperis** [NBISweden/sda-cli#278]
`sda-cli` returns `exit 0` even if errors occurred. E.g.

```
sda-cli list --config nonexistent
Error: failed to load config file, reason: open nonexistent: no such file or directory
echo $?
0
```

See #225 for a related bug in the opposite direction.

**Comment by kusalananda** [comment]
Update your `sda-cli` repository checkout, rebuild, and test again. It works as it should with updated code.

**Comment by aaperis** [comment]
Please excuse my [goldfish memory](https://github.com/NBISweden/sda-cli/commit/58f85283568875246b835e54e73613e2c5569d45)  :sweat_smile: 

The problem was that I was fetching the latest release binary which is a couple of months behind. Closing.
