### ISSUE TITLE
Update README for BP and FEGA when a new version is released

### ISSUE THREAD

**Issue by dbampalikis** [NBISweden/sda-cli#284]
As an sda-dev
I want to have the websites of BP and FEGA updated with the new link of the sda-cli whenever there is a new release
In order for the users to always have the latest version of the cli for submitting data

A/C:
- replace the current link with the one posted below

**Comment by jbygdell** [comment]
`https://github.com/NBISweden/sda-cli/releases/latest` will always give you the latest release page.

**Comment by MalinAhlberg** [comment]
Assumptions:
- BP and FEGA refer to bp.nbis.se and fega.nbis.se, respectively.
- The "README" refers to their user documentation for uploading data.

Problem:
The sda-cli version is used like this on the two webpages:
```
curl -OL https://github.com/NBISweden/sda-cli/releases/download/v0.1.0/sda-cli_.0.1.0_Linux_x86_64.tar.gz
```
See https://bp.nbis.se/datasets/submission/submission-guide.html
That is, it is not a link to the latest releases page, but to an actual download, where the version tag is also included
in the filename itself (`sda-cli_.0.1.0_Linux_x86_64.tar.gz`). Afaik,this cannot be solved by using `latest`.

Suggestion:
- the [release workflow](https://github.com/NBISweden/sda-cli/blob/main/.github/workflows/release.yml) of `sda-cli` is extended to run a bash script, which
  - downloads the bp and fega repos
  - updates their `variables.yml` files to list the newest version of sda-cli
  - creates PRs of this in the two repos
- we would need to create an Organizational Secret for this, giving access to the two repos (bp and fega), to be used by the `sda-cli` workflow.

**Comment by jbygdell** [comment]
```
curl -sL https://api.github.com/repos/NBISweden/sda-cli/releases/latest | jq -r '.assets.[].browser_download_url | select(test("Linux_x86"))'
 ```

This will give you the downloadable URL
