### ISSUE TITLE
Change back the number of approved reviews

### ISSUE THREAD

**Issue by kostas-kou** [NBISweden/sda-cli#416]
For the summer in some repos the needed approvals have been changed to one review because in some periods only two GS developers were working.
Change it back to two after summer when most of the developers are back from their holidays

**Comment by MalinAhlberg** [comment]
- [x] sda-cli
- [x] local-ega-se-deployment
- [x] BigPicture-Deployment
- [x] htsget-rs-helm
- [ ] sensitive-data-archive (don't have access)
