### ISSUE TITLE
[list] Show more metadata information when showing information about datasets

### ISSUE THREAD

**Issue by viklund** [NBISweden/sda-cli#438]
As a user
I want to know a little bit more about a dataset before listing its files
So I can take better decisions for the next step

### Description
Currently when listing datasets only the ids of the datasets are displayed. Would be good to also display the total size of a dataset and the number of files it contains.

A/C:
output as in below

Example:
```
$ sda-cli list --datasets
Dataset      Files    Size
dataset-01     345     50 Gb
dataset-02      12     22 Gb
dataset-03    9821    2.7 Tb
```

**Comment by jbygdell** [comment]
The actual command should be: `sda-cli list-datasets` to clearly show that it is the intent.
