### ISSUE TITLE
Decrypting multiple files with sda-cli impossible when one of the files has been decrypted already

### ISSUE THREAD

**Issue by francescociompi** [NBISweden/sda-cli#446]
**Describe the bug**
Decrypting multiple files with sda-cli breaks when one of the files has been decrypted already.

**Steps to reproduce**
1. make a folder with several encrypted files
2. run sda-cli to decrypt one of the files in the folder
3. run sda-cli again to decrypt all files in that folder; this will cause the command to stop because one file is decrypted

**Expected behavior**
- [ ] 
- [ ] Tests verifying the fix are added

**Additional context**

**Estimation of size**: small/medium/big

**Estimation of priority**: low/medium/high

**Comment by kostas-kou** [comment]
The plan is to fix this by instead of aborting when encountering an already decrypted file the tool will just print a warning and move on to the next file.
