### ISSUE TITLE
MultiPartUpload: upload multipart failed

### ISSUE THREAD

**Issue by mglett** [NBISweden/sda-cli#465]
**Describe the bug**

When uploading a dataset, we received the following error message.

``` bash
File 1.2.826.0.1.3680043.8.498.12434876150204549337819766745345036193.dcm.c4gh: uploading 116.4 MiB / 116.4 MiB done
Error: MultipartUpload: upload multipart failed
	upload id: 2~0xRvPHoe409aEInnZDaPjp2BHKuq0ZZ
caused by: InternalError: This multipart completion is already in progress
	status code: 500, request id: , host id:
```
This happened twice, we tried to upload the same dataset with the --force-overwrite flag. The second time the same error occurred for a different file, however, the upload progressed more.

When uploading a smaller dataset there were no problems (1 Image). 

We currently have not profiled the connection from our side.

**Steps to reproduce**
Unclear.

**Expected behavior**
- [ ] successful upload of the entire dataset
- [ ] Tests verifying the fix are added

**Additional context**

**Estimation of size**: small/medium/big
big
**Estimation of priority**: low/medium/high
high

Kind Regards from the MUW DevTeam

**Comment by viklund** [comment]
I'm closing this because it seems to be related with the deployment and not the sda-cli. Please email bp-ops with these issues instead.
